Feature/signature
denaskhabovG/nestjs-app pull request #2
Opened 2021-09-06 14:26 UTC by denaskhabovG

2021-09-06 15:11 UTC, IslamRustamov1 requested changes

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/app.controller.ts
> +    return 'asasas';
remove this controller completely

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/app.service.ts
>  export class AppService {
remove this service completely

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/config/SequelizeConfigService.ts
> +    } = this.configService.get<IDatabaseConfig>('database');
('database'); move this to enum

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/config/configuration.ts
> +export const databaseConfig = registerAs('database', (): IDatabaseConfig => ({
take 'database' string from enum

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/session/session.module.ts
> +import { ConfigModule } from '@nestjs/config';
Import sequence - first comes official libraries, then yours

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/todos/dto/change-todo.dto.ts
> +  readonly done: boolean;
Add decorators for type validation

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/todos/dto/create-todo.dto.ts
> +  readonly done: boolean;
Add decorators for type validation

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/todos/dto/update-todo.dto.ts
> +  readonly done: boolean;
Add decorators for type validation

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/todos/dto/create-todo.dto.ts
> +  readonly done: boolean;
remove done from create todo dto

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/todos/todos.controller.ts
> +  @Header('Content-Type', 'application/json')
check if this is truly needed

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/todos/todos.controller.ts
> +  changeTodo(@Body() updateTodo: UpdateTodoDto, @Param('id') id: string) {
Id must be passed here

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/userSignature/dto/create-signature.dto.ts
> +  readonly text: string;
need decorators

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/userSignature/userSignature.controller.ts
> +  deleteTodo(@Param('id') id: number) {
I don't think that this fits here

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/userSignature/userSignature.service.ts
> +  decrypt(message = '', key = '') {
move encrypt and decrypt to a different service

2021-09-06 15:11 UTC, IslamRustamov1 commented on src/userSignature/userSignature.service.ts
> +      const decryptedLastSignature = this.decrypt(signature2.text, 'secret');
rename this to decryptedSignature2

2021-09-06 15:28 UTC, denaskhabovG commented on src/userSignature/userSignature.controller.ts
> +  deleteTodo(@Param('id') id: number) {
Do i need delete todo by id?

2021-09-07 15:31 UTC, IslamRustamov1 approved these changes

2021-09-07 15:32 UTC, merged